# Generated by Django 4.0.2 on 2022-05-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bookCIVIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bookCSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bookECE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bookEEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bookMECh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='comices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='entertaiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='issue_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('register_id', models.CharField(max_length=200)),
                ('Author_Name', models.CharField(max_length=300)),
                ('book_id', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
            options={
                'db_table': 'issue_book',
            },
        ),
        migrations.CreateModel(
            name='novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sci_fic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=5)),
                ('book_author', models.CharField(max_length=100)),
                ('book_regulation', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollnumber', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('dept', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.IntegerField()),
                ('author', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=30)),
                ('date', models.DateField(default='2022-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollnumber', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('dept', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_id', models.IntegerField()),
                ('author', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History'), ('novel', 'Novel'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Sci-Fi')], default='education', max_length=30)),
                ('date', models.DateField(default='2022-01-01')),
            ],
        ),
    ]
