# Generated by Django 4.0.2 on 2022-05-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelibrary', '0002_bookcivil_image_bookcse_image_bookece_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(upload_to='image')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
